# Название нашей инструкции для робота
name: Синхронизация из репозитория AI Studio

# Когда роботу нужно начинать работать?
on:
  # По расписанию: каждые 6 часов
  schedule:
    - cron: "0 */6 * * *"
  # А также по нажатию кнопки "Run workflow" во вкладке Actions
  workflow_dispatch:

# Список заданий для робота
jobs:
  # Называем наше единственное задание "sync"
  sync:
    # На каком компьютере будет работать робот (предоставляет GitHub)
    runs-on: ubuntu-latest
    # Шаги, которые нужно выполнить
    steps:
      # Шаг 1: Робот должен сначала "скачать" ваш рабочий репозиторий, чтобы было с чем работать
      - name: Скачиваем рабочий репозиторий
        uses: actions/checkout@v3
        with:
          # Для дальнейшей работы ему понадобится наш секретный ключ
          token: ${{ secrets.GH_PAT }}

     # Шаг 2: Главная работа по синхронизации
      - name: Синхронизируем и отправляем изменения
        run: |
          # Робот представляется системе
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          
          # Робот "запоминает" адрес вашего репозитория от AI
          git remote add upstream https://github.com/kostia-egik/transmissioncalk-aistudio.git
          
          # Робот сначала забирает последние изменения из СВОЕГО ЖЕ рабочего репозитория, на всякий случай
          git pull origin main
          
          # Робот скачивает все из репозитория от AI
          git fetch upstream

          # Робот пытается сделать обычное слияние. Git сам разберется с README и иконкой благодаря .gitattributes
          # Мы добавляем "-X theirs", чтобы в остальных файлах при конфликте выбиралась версия от AI
          git merge -m "Автоматическая синхронизация из AI Studio" -X theirs upstream/main --allow-unrelated-histories

          # ПРИКАЗ: принудительно вернуть старые версии файлов после слияния
          git checkout origin/main -- README.md favicon.png
          
          # Робот отправляет финальный результат обратно
          git push origin main
